services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecomsys
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  book:
    build:
      context: ./book
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./book:/app
  cloth:
    build:
      context: ./cloth
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./cloth:/app
  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./mobile:/app
